# Generated by Django 3.1.7 on 2021-04-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('dispached', 'dispached'), ('canceled', 'canceled')], default='ordered', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.mobile')),
            ],
        ),
    ]
